- include: ../../apache_vhost/tasks/main.yml context_path='{{ ipt_context_path }}' hostname='{{ ipt_hostname }}'
  tags:
    - ipt
    - apache_vhost
    - deploy

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ ipt_war_url }}' context_path='{{ipt_context_path}}' hostname='{{ ipt_hostname }}'
  tags:
    - ipt
    - tomcat_vhost
    - deploy

- name: ensure ipt data directory exists
  file: path={{item}} state=directory mode=0775
  with_items:
    - "{{data_dir}}/ipt"
  tags:
    - ipt
    - ipt_data_dir    

- name: set data ownership [all data is owned by tomcat]
  file: path={{data_dir}}/{{item}} owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  with_items:
    - ipt 
  tags:
    - ipt
    - ipt_data_dir    