- include: ../../common/tasks/setfacts.yml
  tags:
    - webapps
    - config
    - bie

- name: ensure target directories exist
  file: path={{item}} state=directory mode=0775
  with_items:
    - "{{data_dir}}/{{bie_hub}}/config"
  tags:
    - config
    - bie    

- name: copy all config.properties
  template: src=bie-hub-config.properties dest={{data_dir}}/{{bie_hub}}/config/{{bie_hub}}-config.properties force=yes
  tags:
    - webapps
    - config
    - bie

- name: set data ownership [all data is owned by tomcat]
  file: path={{data_dir}}/{{bie_hub}}/ owner={{tomcat_user}} group={{tomcat_user}} recurse=true
  tags:
    - config
    - bie     


- include: ../../apache_vhost/tasks/main.yml context_path='/{{ bie_hub_context_path }}' hostname='{{ bie_hub_hostname }}'
  tags:
    - webapps
    - apache_vhost
    - deploy
    - bie    

- include: ../../tomcat_deploy/tasks/main.yml war_url='{{ bie_hub_war_url }}' context_path='{{ bie_hub_context_path }}' hostname='{{ bie_hub_hostname }}'
  tags:
    - webapps
    - tomcat_vhost
    - deploy
    - bie    
