---
- name: Create the directories for site specific configurations
  file: path={{nginx_conf_dir}}/{{ item }} state=directory owner=root group={{nginx_group}} mode=0755
  with_items:
    - "sites-available"
    - "sites-enabled"
    - "auth_basic"
    - "conf.d"
  tags: [configuration,nginx]

- name: Ensure log directory exist
  file: path={{ nginx_log_dir }} state=directory owner={{nginx_user}} group={{nginx_group}} mode=0755
  tags: [configuration,nginx]

- name: Copy the nginx configuration file
  template: src={{role_path}}/../nginx/templates/nginx.conf.j2 dest={{nginx_conf_dir}}/nginx.conf
  notify:
   - restart nginx
  tags: [configuration,nginx]

- name: Ensure auth_basic files created
  template: src={{role_path}}/../nginx/templates/auth_basic.j2 dest={{nginx_conf_dir}}/auth_basic/{{ item }} owner=root group={{nginx_group}} mode=0750
  with_items: "{{ nginx_auth_basic_files.keys() }}"
  notify:
   - reload nginx
  tags: [configuration,nginx]

- name: Create the configurations for independent config file
  template: src={{role_path}}/../nginx/templates/config.conf.j2 dest={{nginx_conf_dir}}/conf.d/{{ item }}.conf
  with_items: "{{ nginx_configs.keys() }}"
  notify:
   - reload nginx
  tags: [configuration,nginx]

