
nginx_sites:
  1:
    - listen 80
    - listen [::]:80
    - server_name {{ hostname }}
    - "{{ redirect }}"
    - client_max_body_size 500m
    - location /{{ context_path.replace('/', '') }} { proxy_set_header X-Real-IP $remote_addr; proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_pass http://127.0.0.1:8080/{{ context_path.replace('/', '') }}; }

nginx_https_sites:
  1:
    - listen 443 spdy
    - listen [::]:443 spdy
    - server_name {{ hostname }}
    - ssl_certificate {{ ssl_cert_filepath }}
    - ssl_certificate_key {{ ssl_key_filepath }}
    - client_max_body_size 500m
    - location /{{ context_path.replace('/', '') }} { proxy_set_header X-Real-IP $remote_addr; proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_pass http://127.0.0.1:8080/{{ context_path.replace('/', '') }}; }


# Additional proxy pass can be defined in the inventory file depending on the application
#  If it is a static content in nginx server, set proxy_pass to false 
#  otherwise, set this to true if the request is to be passed to another site
#additional_proxy_pass:
#  - { src: "/example", dest: "/var/www", proxy_pass: false }
#  - { src: "/test", dest: "http://127.0.0.1:8080/", proxy_pass: true }